# Generated by Django 3.0.7 on 2020-06-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ing', models.TextField()),
                ('recipt', models.TextField()),
                ('Author', models.CharField(max_length=255)),
            ],
        ),
    ]
